### ISSUE TITLE
did not receive email confirmation

### ISSUE THREAD

**Issue by guoard** [mshirdel/gapbug#6]
ثبت نام کردم ولی متاسفانه ایمیلی دریافت نکردم.

**Comment by mshirdel** [comment]
به نظر میرسه موقع ثبت نام ایمیل وارد نکردید. این البته باگ بزرگی هست. میشه بیشتر توضیح بدید که چطوری ثبت نام کردید. کاربر ایجادشده ولی ایمیلی ثبت نشده.

**Comment by guoard** [comment]
ایمیل رو که مطمئنا وارد کردم و از طریق فرم ثبت نام سایت ثبت نام کردم

**Comment by mshirdel** [comment]
ممنون از گزارش باگ. مشکل برطرف شد. کاربر قبلی رو پاک کردم یک بار دیگه کاربر جدید بسازید.

**Comment by guoard** [comment]
ممنون
